### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by muntakimrafi** [UBC-MDS/525_group_14#17]
Missing Team-work contract in canvas submission (-10)
Good Job on the assignment! (90/100)

Feel free to send me your teamwork contract in this issue to receive the deducted mark!

**Comment by eyrexh** [comment]
Hi @muntakimrafi  ,

I have submitted the link to the teamwork contract in my submission. I think Gittu reset the formatting later because Canvas cannot show everyone submitted files, and I do not know maybe that cause some problems to show our teamwork contract. Please check my screenshots for my submission.

**Comment by muntakimrafi** [comment]
Thanks! regraded (100/100)
